name: 'M6A'
repo: 'http://github.com/gaow/m6a'
footer: "&copy 2016-2017 Min Qiao at He Lab, University of Chicago"
include_dir: ['analysis']
homepage: "writeup/Overview.ipynb"
# post_release_actions: "cd writeup/8687161qzfgsmmjwvzy && git pull" 
add_commit_info: True
notebook_toc: True
reverse_autoindex: ['analysis']
release_message: "Build website with jnbinder"
